In [6]:
import pandas as pd
import matplotlib.pyplot as plt
import datetime as dt

In [ ]:
conda install -c conda-forge pandas-profiling -y

In [24]:
df = pd.read_csv("d:/dados/movimento_de_compra.csv",sep=";",low_memory=False)

In [27]:
df

,chave_nfe_sai,codi_emp,razao_emp,cgce_emp,sigl_est,codi_pdi,desc_pdi,cncm_pdi,nume_sai,ddoc_sai,...,valor_unit_msp,vdesace_msp,vfre_msp,bicmsst_msp,aliq_st_msp,valor_subtri_msp,codi_acu,nome_acumulador,vdes_msp,cat_dpi
0,43220302354197000192650670000199271000305155,236,BRUNETTO COMÉRCIO DE ALIMENTOS LTDA.,2147483647,RS,78989901985472,CLDO MAGGI 57g GALIN,21041011,19927,2022-03-01,...,"1,99",0,0,0,0,0,202,VENDA DE MERCADORIAS S/ ST,0,NaN
1,43220302354197000192650670000199281000305160,236,BRUNETTO COMÉRCIO DE ALIMENTOS LTDA.,2147483647,RS,305,BANANA CATURRA kg,8039000,19928,2022-03-01,...,"2,79",0,0,0,0,0,202,VENDA DE MERCADORIAS S/ ST,0,NaN
2,43220302354197000192650670000199281000305160,236,BRUNETTO COMÉRCIO DE ALIMENTOS LTDA.,2147483647,RS,86151,ALFACE LISA SENTIER,7069000,19928,2022-03-01,...,"2,99",0,0,0,0,0,202,VENDA DE MERCADORIAS S/ ST,0,NaN
3,43220302354197000192650670000199281000305160,236,BRUNETTO COMÉRCIO DE ALIMENTOS LTDA.,2147483647,RS,78989901988855,ACTIVIA AVEIA 850g,4039000,19928,2022-03-01,...,"10,99",0,0,0,0,0,203,VENDA DE MERCADORIAS C/ ST,0,NaN
4,43220302354197000192650670000199281000305160,236,BRUNETTO COMÉRCIO DE ALIMENTOS LTDA.,2147483647,RS,78989901990257,MORT. PERD. CT 400g,16010000,19928,2022-03-01,...,"3,49",0,0,0,0,0,203,VENDA DE MERCADORIAS C/ ST,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
575214,43220302354197000192650620004368741006413852,236,BRUNETTO COMÉRCIO DE ALIMENTOS LTDA.,2147483647,RS,78989902002464,BEB LAC BIO LAT 900g,22029900,436874,2022-03-31,...,"3,69",0,0,0,0,0,203,VENDA DE MERCADORIAS C/ ST,0,NaN
575215,43220302354197000192650620004368741006413852,236,BRUNETTO COMÉRCIO DE ALIMENTOS LTDA.,2147483647,RS,78989902002464,BEB LAC BIO LAT 900g,22029900,436874,2022-03-31,...,"3,69",0,0,0,0,0,203,VENDA DE MERCADORIAS C/ ST,0,NaN
575216,43220302354197000192650620004368741006413852,236,BRUNETTO COMÉRCIO DE ALIMENTOS LTDA.,2147483647,RS,78989902002817,GRAN. TROP 200g FITO,19041000,436874,2022-03-31,...,"6,99",0,0,0,0,0,203,VENDA DE MERCADORIAS C/ ST,0,NaN
575217,43220302354197000192650620004368741006413852,236,BRUNETTO COMÉRCIO DE ALIMENTOS LTDA.,2147483647,RS,78989902004571,GRAN. SAC 200g FITO,19041000,436874,2022-03-31,...,"6,25",0,0,0,0,0,203,VENDA DE MERCADORIAS C/ ST,0,NaN
575218,43220302354197000192650620004368741006413852,236,BRUNETTO COMÉRCIO DE ALIMENTOS LTDA.,2147483647,RS,78989902006022,GRAN. LIGHT 200g FIT,19041000,436874,2022-03-31,...,"5,99",0,0,0,0,0,203,VENDA DE MERCADORIAS C/ ST,0,NaN

In [28]:
selecao = df[{"codi_pdi","desc_pdi","cncm_pdi","nume_sai","ddoc_sai","vpro_msp","cat_dpi"}]

In [29]:
selecao.to_csv('movimento.csv', index=False)

In [32]:
df = pd.read_csv("movimento.csv",low_memory=False)

In [34]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 575219 entries, 0 to 575218
Data columns (total 7 columns):
 #   Column    Non-Null Count   Dtype
---  ------    --------------   -----
 0   codi_pdi  575219 non-null  object
 1   ddoc_sai  575219 non-null  object
 2   cat_dpi   192486 non-null  object
 3   desc_pdi  575219 non-null  object
 4   nume_sai  575219 non-null  int64
 5   vpro_msp  575219 non-null  object
 6   cncm_pdi  575219 non-null  int64
dtypes: int64(2), object(5)
memory usage: 30.7+ MB

In [35]:
df = df.rename({'codi_pdi': 'cod_produto','ddoc_sai':'data_compra','cat_dpi':'categoria','desc_pdi':'desc_produto','nume_sai':'id_compra','vpro_msp':'valor_produto','cncm_pdi':'ncm_produto'}, axis = 1)

In [38]:
df.dropna

In [45]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 192486 entries, 5 to 575212
Data columns (total 7 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   cod_produto    192486 non-null  object
 1   data_compra    192486 non-null  object
 2   categoria      192486 non-null  object
 3   desc_produto   192486 non-null  object
 4   id_compra      192486 non-null  int64
 5   valor_produto  192486 non-null  float64
 6   ncm_produto    192486 non-null  int64
dtypes: float64(1), int64(2), object(4)
memory usage: 11.7+ MB

In [52]:
df

,cod_produto,data_compra,categoria,desc_produto,id_compra,valor_produto,ncm_produto
5,78989901987026,2022-03-01,LATICINIOS,BISC RECH 115GR GLUB,19929,1.19,19053100
7,78989902002358,2022-03-01,LATICINIOS,LEITE DALIA INT 1LT,19930,3.29,4012010
25,78989902006136,2022-03-01,LIMPEZA,L.R UZZILIM 1kg LAVA,19933,4.99,34029090
27,6081,2022-03-01,CARNES,AGULHA BOV SO kg,19933,33.43,2012090
28,71511,2022-03-01,BEBIDAS,REF 3LT FANTA GUARAN,19933,6.99,22021000
...,...,...,...,...,...,...,...
575208,69176,2022-03-31,LATICINIOS,CISC TRAK CHOC BR 12,436874,2.39,19053100
575209,69176,2022-03-31,LATICINIOS,CISC TRAK CHOC BR 12,436874,2.39,19053100
575210,74208,2022-03-31,LATICINIOS,WAF ISABELA 100g CHO,436874,1.99,19053200
575211,74208,2022-03-31,LATICINIOS,WAF ISABELA 100g CHO,436874,1.99,19053200
575212,74210,2022-03-31,LATICINIOS,WAF ISABELA 100g MG,436874,1.99,19053200

In [48]:
df_ncm = pd.read_csv("d:/dados/tabela_reduzida_ncm.csv",sep=";")

In [50]:
df_ncm.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   id         7 non-null      int64
 1   categoria  7 non-null      object
 2   lista_cnm  7 non-null      object
dtypes: int64(1), object(2)
memory usage: 296.0+ bytes

In [51]:
df_ncm

   id        categoria                                          lista_cnm
0   1           CARNES  20120,20130,20230,20312,20319,20329,20629,2071...
1   2          BEBIDAS          22011,22021,22030,22041,22042,22086,22060
2   3       LATICINIOS                      40110,40120,40150,40610,19053
3   4          LIMPEZA  28289,68051,68053,39232,33029,96039,29039,3808...
4   5          CEREAIS  10063,90300,71333,71340,11010,17011,11062,1104...
5   6  HIGIENE_PESSOAL    33043,96019,96032,96033,34011,33051,33061,33071
6   7              PET                                        23099,42010

In [55]:
df.isnull().sum()

cod_produto      0
data_compra      0
categoria        0
desc_produto     0
id_compra        0
valor_produto    0
ncm_produto      0
dtype: int64